Repository CloudVLab/terraform-lab-foundation, pull requests merged in 2022-08, with the labels that each got.

#173 Tlf maintenance
  solutions/proxy_vertex_workbench/stable/main.tf
  solutions/proxy_vertex_workbench/stable/variables.tf
Labels: bug, documentation, enhancement

#174 Fix: invalid variable definition
  solutions/proxy_vertex_workbench/stable/variables.tf
Labels: bug, documentation, enhancement

#175 Add: install and example doc
  basics/gcs_bucket/example/install.sh
  basics/gcs_bucket/example/main.tf
  basics/gcs_bucket/example/variables.tf
Labels: documentation, enhancement, help wanted

#176 Add: update assigned location
  solutions/proxy_vertex_workbench/stable/main.tf
Labels: bug, documentation, enhancement

#177 Add: Amend from region to zone
  solutions/proxy_vertex_workbench/stable/main.tf
Labels: bug, documentation, help wanted

#178 Tlf maintenance
  solutions/proxy_automl/example/outputs.tf
  solutions/proxy_automl/stable/outputs.tf
Labels: bug, documentation, enhancement

#179 Add: default value for Username
  solutions/ide_web/stable/variables.tf
Labels: bug, documentation, enhancement

#180 Add: Version revision
  basics/gke_cluster/example/README.md
  basics/gke_cluster/example/install.sh
  basics/gke_cluster/example/main.tf
  basics/gke_cluster/example/outputs.tf
  basics/gke_cluster/example/runtime.yaml
  basics/gke_cluster/example/variables.tf
  basics/gke_cluster/stable/main.tf
  basics/gke_cluster/stable/variables.tf
Labels: documentation, enhancement

#181 Fix: workbench proxy vpc connector name gen
  solutions/proxy_vertex_workbench/stable/main.tf
Labels: bug, documentation, enhancement
