Repository CloudVLab/terraform-lab-foundation, pull requests merged in 2024-10, with the labels that each got.

#418 use Workbench Instances instead of User-Managed Instances for the generative-ai solution
  solutions/generative-ai/stable/main.tf
Labels: enhancement

#420 Revert "removed provider from child modules to prevent module loading issues"
  basics/iam_role_bind/stable/provider.tf
  basics/iam_sa_role/stable/provider.tf
  basics/iam_service_account/stable/provider.tf
Labels: bug

#422 hotfix: gce instance variable default should be null
  basics/gce_instance/stable/variables.tf
Labels: bug

#424 Tlf cr
  basics/cloud_function/stable/main.tf
  basics/cloud_function/stable/variables.tf
Labels: bug, documentation, enhancement
